user/create:
 - field: login_id
   label: label_user_login_id
   rules: trim|required|alpha_numeric|min_length[6]|max_length[64]|is_unique[users.login_id]|is_unique[tmp_users.login_id]|xss_clean
   
 - field: password
   label: label_user_password
   rules: trim|required|alpha_numeric|min_length[7]|max_length[255]|xss_clean
   
 - field: re_password
   label: label_user_re_password
   rules: trim|required|alpha_numeric|min_length[7]|max_length[255]|confirm_pasword_matches[re_password]|xss_clean
   
 - field: email
   label: label_user_email
   rules: trim|required|valid_email|max_length[128]|xss_clean
   
 - field: birthday
   label: label_user_birthday
   rules: trim|is_selected|xss_clean
   
 - field: gender
   label: label_user_gender
   rules: trim|is_selected|xss_clean
   
 - field: qualification_id
   label: label_user_qualifications_job
   rules: trim|is_selected|xss_clean
   
 - field: organization
   label: label_user_organization
   rules: trim|required|max_length[255]|xss_clean
user/create_lang_japanese:
 - field: first_name_ja
   label: label_user_first_name_ja
   rules: trim|required|max_length[64]|xss_clean

 - field: last_name_ja
   label: label_user_last_name_ja
   rules: trim|required|max_length[64]|xss_clean
   
 - field: first_name
   label: label_user_first_name
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean
   
 - field: last_name
   label: label_user_last_name
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean
user/create_lang_english:
 - field: first_name
   label: label_user_first_name_ja
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean

 - field: last_name
   label: label_user_last_name_ja
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean
user/create_general:
 - field: auth_method
   label: label_user_auth_method
   rules: trim|is_selected|xss_clean
user/auth_info:
 - field: confirm_phone_number
   label: label_user_confirm_phone_number
   rules: trim|required|is_valid_phone_number|xss_clean
   
 - field: confirm_organization
   label: label_user_confirm_organization
   rules: trim|required|xss_clean

user/edit:
 - field: login_id
   label: label_user_login_id
   rules: trim|required|alpha_numeric|min_length[6]|max_length[64]|callback_check_login_id|xss_clean
   
 - field: email
   label: label_user_email
   rules: trim|required|valid_email|max_length[128]|xss_clean
   
 - field: birthday
   label: label_user_birthday
   rules: trim|required|xss_clean
   
 - field: gender
   label: label_user_gender
   rules: trim|required|xss_clean
   
 - field: qualification_id
   label: label_user_qualifications_job
   rules: trim|required|xss_clean
   
 - field: organization
   label: label_user_organization
   rules: trim|max_length[255]|xss_clean
   
 - field: phone_number
   label: label_user_phone_number
   rules: trim|is_valid_phone_number|xss_clean
   
 - field: specialist
   label: label_user_specialist
   rules: trim|max_length[255]|xss_clean
   
 - field: domain
   label: label_user_domain
   rules: trim|max_length[255]|xss_clean
   
 - field: university
   label: label_user_university
   rules: trim|max_length[255]|xss_clean
   
 - field: history
   label: label_user_history
   rules: trim|max_length[20000]|xss_clean
   
 - field: hobby
   label: label_user_hobby
   rules: trim|max_length[20000]|xss_clean

 - field: message
   label: label_user_hobby
   rules: trim|max_length[20000]|xss_clean
   
 - field: society
   label: label_user_society
   rules: trim|max_length[20000]|xss_clean
   
 - field: author
   label: label_user_author
   rules: trim|max_length[20000]|xss_clean
   
 - field: scholar
   label: label_user_scholar
   rules: trim|max_length[20000]|xss_clean
user/edit_email:
 - field: email
   label: label_user_email
   rules: trim|required|valid_email|is_unique_email_registered[users.email]|is_unique_email_request[users.email]|is_unique_email_invite[users.email]|xss_clean
user/edit_mode_japanese:
 - field: first_name_ja
   label: label_user_first_name_ja
   rules: trim|required|max_length[64]|xss_clean

 - field: last_name_ja
   label: label_user_last_name_ja
   rules: trim|required|max_length[64]|xss_clean
   
 - field: first_name
   label: label_user_first_name
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean
   
 - field: last_name
   label: label_user_last_name
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean
user/edit_mode_english:
 - field: first_name
   label: label_user_first_name_ja
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean

 - field: last_name
   label: label_user_last_name_ja
   rules: trim|required|alpha_numeric|max_length[64]|xss_clean
user/change_password:
 - field: password
   label: label_user_password
   rules: trim|required|alpha_numeric|min_length[7]|max_length[255]|xss_clean
   
 - field: re_password
   label: label_user_re_password
   rules: trim|required|alpha_numeric|min_length[7]|max_length[255]|confirm_pasword_matches[re_password]|xss_clean
user/invite:
 - field: email
   label: label_post_invite_email_address
   rules: trim|required|max_length[128]|valid_email|is_unique_email_registered[users.email]|is_unique_email_request[users.email]|is_unique_email_invite[users.email]|xss_clean

 - field: first_name_ja
   label: label_user_first_name_ja
   rules: trim|required|max_length[64]|xss_clean

 - field: last_name_ja
   label: label_user_last_name_ja
   rules: trim|required|max_length[64]|xss_clean